apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: platform
  source:
    repoURL: https://github.com/UOM-CSE-Sem4-GroupF/group-f-platform.git
    targetRevision: main
    path: monitoring/elk/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
