apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-processor
  namespace: cicd
  labels:
    project: group-f-swms
    managed-by: f4-platform
    component: waste-dev
  annotations:
    argocd.argoproj.io/sync-wave: "20" # Deploy after databases
spec:
  project: platform

  source:
    repoURL: https://github.com/UOM-CSE-Sem4-GroupF/group-f-platform
    targetRevision: main
    path: helm/charts/base-service
    helm:
      releaseName: flink-processor
      valueFiles:
        # Resolve the values file relative to the chart directory.
        # Since the chart is in helm/charts/base-service, we go up three levels to reach waste-dev.
        - ../../../waste-dev/flink-processor/values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: waste-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
