apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: cicd
  labels:
    project: group-f-swms
    managed-by: f4-platform
    component: waste-dev
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform

  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: influxdb
      targetRevision: "5.2.4"
      helm:
        releaseName: influxdb
        valueFiles:
          - $values/waste-dev/influxdb/values-dev.yaml

    - repoURL: https://github.com/UOM-CSE-Sem4-GroupF/group-f-platform
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: waste-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
