apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: cicd
  labels:
    project: group-f-swms
    managed-by: f4-platform
    component: networking
  annotations:
    argocd.argoproj.io/sync-wave: "-5" # Ensure CRDs are installed first
spec:
  project: platform
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.22.0
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
