apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-waste
  namespace: cicd
  labels:
    project: group-f-swms
    managed-by: f4-platform
    component: waste-dev
  annotations:
    argocd.argoproj.io/sync-wave: "10" # Deploy after basic infrastructure
spec:
  project: platform

  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: "18.6.2"
      helm:
        releaseName: postgres-waste
        valueFiles:
          - $values/waste-dev/postgres-waste/values-dev.yaml

    - repoURL: https://github.com/UOM-CSE-Sem4-GroupF/Smart-Waste-Management-System-Platform
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: waste-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
