apiVersion: argocd.argoproj.io/v1alpha1
kind: Application
metadata:
  name: f3-scheduler
  namespace: cicd
spec:
  project: platform
  source:
    repoURL: https://github.com/UOM-CSE-Sem4-GroupF/Smart-Waste-Management-System-Platform
    targetRevision: main
    path: apps/scheduler
    helm:
      releaseName: scheduler
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: waste-dev
  syncPolicy:
    automated: { prune: true, selfHeal: true }
