replicaCount: 1

imagePullSecrets:
  - name: ghcr-pull-secret

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: false
  size: 500Mi
