apiVersion: v2
name: airflow
description: Helm chart for airflow
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: base-service
    version: 1.0.0
    repository: "file://../../helm/charts/base-service"
