# Inherited from base-service
base-service:
  imagePullSecrets:
    - name: ghcr-pull-secret
  image:
    repository: ghcr.io/uom-cse-sem4-groupf/airflow
    tag: latest
  service:
    port: 8080
  command: ["airflow", "webserver"]

  env:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////tmp/airflow.db"
    AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
    PORT: "8080"

  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10

  containerSecurityContext:
    readOnlyRootFilesystem: false
    runAsUser: 50000 # Official airflow user UID is 50000

