# Inherited from base-service
base-service:
  imagePullSecrets:
    - name: ghcr-pull-secret
  image:
    repository: ghcr.io/uom-cse-sem4-groupf/spark
    tag: latest
  service:
    port: 8080
  livenessProbe:
    enabled: false
    httpGet:
      port: 8080
      path: /
  readinessProbe:
    enabled: false
    httpGet:
      port: 8080
      path: /
  env:
    HOME: "/tmp"
    PORT: "8080"

  containerSecurityContext:
    readOnlyRootFilesystem: false

  extraVolumeMounts:
    - name: tmp-dir
      mountPath: /tmp
  extraVolumes:
    - name: tmp-dir
      emptyDir: {}
