apiVersion: v2
name: flink-processor
description: All 5 Flink stream processing pipelines in a single pod
type: application
version: 1.0.0
dependencies:
  - name: base-service
    version: 1.0.0
    repository: "file://../../helm/charts/base-service"
