apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-service.fullname" . }}-config
data:
  APP_ENV: "dev"
  LOG_LEVEL: "info"
  {{- if .Values.env }}
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
