# Inherited from base-service
base-service:
  image:
    repository: ghcr.io/uom-cse-sem4-groupf/ml-service
    tag: latest
  service:
    port: 8000
  livenessProbe:
    enabled: true
    httpGet:
      port: 8000
      path: /health
  readinessProbe:
    enabled: true
    httpGet:
      port: 8000
      path: /health

  env:
    APP_ENV: "production"
    LOG_LEVEL: "INFO"
    ML_SERVICE_FALLBACK_MODE: "true"
    MLFLOW_TRACKING_URI: ""
    POSTGRES_HOST: "postgres-waste-postgresql.waste-dev.svc.cluster.local"
    POSTGRES_PORT: "5432"
    POSTGRES_DB: "waste_management"
    POSTGRES_USER: "waste_admin"

  externalSecret:
    enabled: true
    vaultPath: swms/postgres-waste
    secretStoreName: vault-backend
    secretStoreKind: ClusterSecretStore
    data:
      - secretKey: POSTGRES_PASSWORD
        remoteRef: { key: swms/postgres-waste, property: password }
