# F2 Application Services (DigitalOcean)
# InfluxDB
# Namespace: waste-dev

image:
  registry: ghcr.io
  repository: bitnami/influxdb

auth:
  admin:
    username: admin
    password: admin12345
    token: my-super-token
    org: waste-org
    bucket: waste-bootstrap

persistence:
  storageClass: do-block-storage

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
