apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-user-passwords
  namespace: messaging
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kafka-user-passwords
    creationPolicy: Owner
  data:
    - secretKey: client-username
      remoteRef:
        key: swms/kafka
        property: sasl_username
    - secretKey: client-passwords
      remoteRef:
        key: swms/kafka
        property: sasl_password
